### ISSUE TITLE
Website adjusts to video size rather than video to screen size

### ISSUE THREAD

**Issue by josh-the-tech** [roballsopp/vtt-creator#16]
Love this website, it's really helping out with our training we're developing. Our videos are high res due to them being screen recordings for a High DPI phone and when opening the video, the player changes size to accommodate the full size of the video rather than making the video fit within the size of the screen being worked on (hope this makes sense). I've attached a picture example.
![opera_2020-03-26_12-30-11](https://user-images.githubusercontent.com/7712524/77647116-c1a9e500-6f5d-11ea-92d7-59e996d31ae2.png)

**Comment by roballsopp** [comment]
Hey, thanks for pointing this out! Looks like I some work to do in general on the responsiveness of the video player. I'll keep you updated...

**Comment by josh-the-tech** [comment]
Thanks very much, this is helping us quite a lot as we're developing training materials for our teams whilst they're off the road!

**Comment by roballsopp** [comment]
Just deployed what I hope is a fix for this. Let me know if its looking better for you after a page refresh.

**Comment by josh-the-tech** [comment]
Thanks Rob. Just tried it on the new Chromium based edge on a Remote Desktop session and it looks like it’s working. Will be able to try properly on Monday morning. Thanks!
  
  

 Kind Regards,  

  
Josh Hancock
  
  
  
  

  
  
>

**Comment by josh-the-tech** [comment]
Sorry for delay, just been able to test and it's working perfectly now! Thanks very much!
