### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by afrocubanito** [roballsopp/vtt-creator#38]
Hello,

I try to follow your install instruction for vtt frontend. However it's not working.
I have a blank site, when I go to http://localhost:3000

Best regards

**Comment by roballsopp** [comment]
Hey there. To be honest, I didn't really think anyone would try to run this locally or attempt to contribute, so I haven't kept the readme very up to date. I mostly have this here as a portfolio piece. If you're interested in actually running it locally, you'll need to run the [api](https://github.com/roballsopp/vtt-creator-backend), and set up at the very least an AWS Cognito User Pool (and possibly a Paypal business account), and then inject the environment variables the app needs during build [here](https://github.com/roballsopp/vtt-creator/blob/master/webpack.dev.js#L38). If you are just interested in actually using the app, and not so much seeing how it works or contributing just head over to [vtt-creator.com](https://www.vtt-creator.com/).

**Comment by afrocubanito** [comment]
Thank you for your answer. You did a nice work. I was looking for an user friendly web app, self-hosted, to create manually some captions.
Do you think it's possible to have a version without signup ? So no need of AWS or Paypal?

**Comment by roballsopp** [comment]
I mean, you can fork the repo, then anything is possible. If you want to use the code as-is, you'll need all of that set up, plus a Google Cloud account with the Speech to Text api enabled if you want to use the caption extraction feature.
