### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pwab** [roballsopp/vtt-creator#67]
> I mean, you can fork the repo, then anything is possible. [...]
> 
> _Originally posted by @roballsopp in https://github.com/roballsopp/vtt-creator/issues/38#issuecomment-742145049_

Based on this: What is the license of this project?

I was only able to find one line containing `"license": "ISC"` inside the `package.json` but no copyright notice inside the files or any license file inside the repository.

**Comment by roballsopp** [comment]
Sorry I haven't really looked into licensing. I'm leaving this unlicensed for now. Its kind of just up here for my portfolio.
